apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wit43tkmm-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:2c71b6c6f9ed7af14d07747c6bfdc7361d07d37e@sha256:8d0c8cdf77cd4d7532202e75fea68762a1a4169f3d3e814ebf6e1d5544822f45
          name: container-image
